# Generated by Django 4.1.6 on 2023-02-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='names',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surnames',
            field=models.CharField(blank=True, max_length=80, verbose_name='Apellidos'),
        ),
    ]
